### ISSUE TITLE
Rate Limited when searching for articles in specific language? 

### ISSUE THREAD

**Issue by pdsmith1223** [EventRegistry/event-registry-python#39]
I'm utilizing the code below to search for articles for a list of topics. This method works fine, but as soon as I add the lang argument, the api suddenly starts rate limiting me. Why is this happening? Code is below:

def get_articles(keyList):
    alist = []
    for key in keyList:
        q = QueryArticlesIter(conceptUri = er.getConceptUri(key), lang='eng')
        for article in q.execQuery(er, articleBatchSize = 10, ):
            alist.append(article)
    return alist

**Comment by gregorleban** [comment]
Hi,

we are not rate limiting you if you're searching using the lang parameter. The likely reason for slow response is that for some of your keys we don't return a concept URI (since the concept for your key might not exist) and in that case you're simply searching with the language as the filter. Since there are 100 million news articles, in English, the sorting of the resulting articles takes some time.

I suggest that you first check if the concept uri for your key exists and if not you simply add keywords = key instead of the conceptUri parameter.
