### ISSUE TITLE
Get articles by URI broken

### ISSUE THREAD

**Issue by nwself** [EventRegistry/event-registry-python#60]
Getting articles as in [the example in this repo](https://github.com/EventRegistry/event-registry-python/blob/master/eventregistry/examples/QueryArticlesExamples.py#L48)

```python
q = QueryArticles.initWithArticleUriList(["934903913", "934902493", "934902499", "934902488", "934899375", "934900984", "934890360", "934888250"])
res = er.execQuery(q)
```

is returning 

```json
{"error": "Requested information is not available"}
```

How can I get article data from a list of article URIs?

**Comment by gregorleban** [comment]
The request works normally, you just need to have access to the historical data available to retrieve the articles with those URIs since they have been published many years ago. 

If you create er instance with 

```er = EventRegistry(allowUseOfArchive=False)
```
or have access to historical data disabled in your account setting then you can still use this feature but make sure you try to retrieve articles that have not been published > 1 month ago.

**Comment by nwself** [comment]
That was it! Thanks!
