### ISSUE TITLE
How to exclude the list URI when using Search Articles

### ISSUE THREAD

**Issue by lytaitruong** [EventRegistry/event-registry-python#67]
Hi, I've read your [API documentation](https://www.newsapi.ai/documentation?tab=searchArticles)

We using via your [NodeJS SDK](https://github.com/EventRegistry/event-registry-node-js) to:

   - Search [Articles](https://www.newsapi.ai/documentation?tab=searchArticles)
   - Search [News](https://www.newsapi.ai/documentation?tab=searchEvents)

In search articles, Do we have any filter to exclude the URI itself instead of using SourceURI or EventURI ?
Because sometime I see the eventURI is null

Thank if have any suggestion.

**Comment by gregorleban** [comment]
Hi,

can you maybe clarify the issue?

The articles that you receive can have eventUri = null. That is to be expected. It happens when an article does not belong to any event.

What specifically are you looking to achieve? Remove articles that have a specific eventUri? Remove articles that have eventUri = null? You can exclude articles using a long list of available filters - the same filters as you would otherwise use to determine which things you do want to receive. In that case you simply put the conditions inside the $not segment of the query.

Please let me know what more details I can provide.

Best,
Gregor

**Comment by lytaitruong** [comment]
Hi @gregorleban , I wrong the SDK. I'm using NodeJS so I will communication in another github

Close this issue

Thank and best regards
